{
 "title": "Schelly Backups",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful Backups",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "range",
   "targets": [
    {
     "expr": "schelly_backup_materialized_total{status=\"success\"}"
    }
   ]
  },
  {
   "title": "Backup Errors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "range",
   "targets": [
    { "expr": "sum(schelly_backup_warn_total)" }
   ]
  },
  {
   "title": "Last backup size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "schelly_backup_last_size_mbytes"
    }
   ]
  },
  {
   "title": "Backups deleted (by retention policy)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "schelly_retention_backup_delete_total"
    }
   ]
  },
  {
   "title": "Last backup duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "schelly_backup_last_time_seconds"
    }
   ]
  },
  {
   "title": "Webhook average time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "schelly_webhook_invocation_sum/schelly_webhook_invocation_count"
    }
   ]
  },
  {
   "title": "Retention tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "schelly_retention_tasks_total" }
   ]
  },
  {
   "title": "Backups tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "schelly_backup_tasks_total" }
   ]
  }
 ]
}